using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class TBL_DESK : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new TBL_DESK(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new TBL_DESK(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5429654650092666533UL,2168341108599780744UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public ColorType ColorType
	{
		get => (ColorType) _ColorType[Index];
		set => _ColorType[Index] = value;
	}
	public UnityEngine.Texture2D FrontImage => _FrontImage[Index];
	public UnityEngine.Texture2D BackImage => _BackImage[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5308571660289230339UL, 6529864186668184990UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_ColorType;
	public static BansheeGz.BGDatabase.BGFieldEnum _ColorType => _ufle12jhs77_ColorType ?? (_ufle12jhs77_ColorType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5634912656761620796UL, 6515629903623078315UL), () => _ufle12jhs77_ColorType = null));
	private static BansheeGz.BGDatabase.BGFieldUnityTexture2d _ufle12jhs77_FrontImage;
	public static BansheeGz.BGDatabase.BGFieldUnityTexture2d _FrontImage => _ufle12jhs77_FrontImage ?? (_ufle12jhs77_FrontImage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityTexture2d>(MetaDefault, new BGId(5233580452047345207UL, 10292235017792995003UL), () => _ufle12jhs77_FrontImage = null));
	private static BansheeGz.BGDatabase.BGFieldUnityTexture2d _ufle12jhs77_BackImage;
	public static BansheeGz.BGDatabase.BGFieldUnityTexture2d _BackImage => _ufle12jhs77_BackImage ?? (_ufle12jhs77_BackImage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityTexture2d>(MetaDefault, new BGId(5331987730264795202UL, 1700517985147351948UL), () => _ufle12jhs77_BackImage = null));
	private static readonly TBL_DESK.Factory _factory0_PFS = new TBL_DESK.Factory();
	private TBL_DESK() : base(MetaDefault)
	{
	}
	private TBL_DESK(BGId id) : base(MetaDefault, id)
	{
	}
	private TBL_DESK(BGMetaEntity meta) : base(meta)
	{
	}
	private TBL_DESK(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static TBL_DESK FindEntity(Predicate<TBL_DESK> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((TBL_DESK) entity)) as TBL_DESK;
	}
	public static List<TBL_DESK> FindEntities(Predicate<TBL_DESK> filter, List<TBL_DESK> result=null, Comparison<TBL_DESK> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<TBL_DESK> action, Predicate<TBL_DESK> filter=null, Comparison<TBL_DESK> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((TBL_DESK) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((TBL_DESK) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((TBL_DESK)e1,(TBL_DESK)e2));
	}
	public static TBL_DESK GetEntity(BGId entityId) => (TBL_DESK) MetaDefault.GetEntity(entityId);
	public static TBL_DESK GetEntity(int index) => (TBL_DESK) MetaDefault[index];
	public static TBL_DESK GetEntity(string entityName) => (TBL_DESK) MetaDefault.GetEntity(entityName);
	public static TBL_DESK NewEntity() => (TBL_DESK) MetaDefault.NewEntity();
	public static TBL_DESK NewEntity(BGId entityId) => (TBL_DESK) MetaDefault.NewEntity(entityId);
	public static TBL_DESK NewEntity(Action<TBL_DESK> callback)
	{
		return (TBL_DESK) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((TBL_DESK)entity)));
	}
}
#pragma warning restore 414
